server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource: 
    url: jdbc:mysql://meliexamen.cpiqgxyj55nc.us-east-1.rds.amazonaws.com:3306/mutants
    username: admin
    password: Luis1984 
logging:
  level:
    org:
      hibernate:
        SQL: debug